Add Forgot Password Form
AlanMorel/aria pull request #7
Opened 2019-12-02 11:49 UTC by holthelper

- Simple forgotten password form

2019-12-03 04:11 UTC, AlanMorel requested changes

2019-12-03 04:11 UTC, AlanMorel commented on src/components/login/Login.js
> +      event.preventDefault();
Indentation in all these files should be 4 spaces instead of 2 to keep it consistent with the rest of the code base

2019-12-03 04:11 UTC, AlanMorel commented on src/components/login/Login.js
> +                      <a id="forgotten" href="#" onClick={this.handleClick.bind(this)}>Forgot Password?</a>
`forgotten` should be a class, not an ID

2019-12-03 04:11 UTC, AlanMorel commented on src/components/login/Login.scss
> +    margin-top: 1em;
Use the `rem` unit

2019-12-03 04:11 UTC, AlanMorel commented on src/components/login/Login.scss
> +    font-family: "Montserrat", sans-serif;
Use the font-family variable already defined for this

2019-12-03 04:11 UTC, AlanMorel commented on src/components/login/Login.scss
> +  #forgotten {
This shouldn't be nested and instead should live at the root

2019-12-03 04:11 UTC, AlanMorel commented on src/components/reset/Reset.js
> +    Axios.post('reset', form).then((response) => {
`'reset'` should be double quotes

2019-12-03 04:11 UTC, AlanMorel commented on src/components/navigation/prompts/Prompts.js
> +                <a href="/#" onClick={this.openJoin} className="prompt-button">Join</a>
This should probably just be a `span` or `div` at this point

2019-12-03 04:11 UTC, AlanMorel commented on src/components/join/Join.js
> +                        <ReCAPTCHA className="recaptcha" ref={(r) => this.recaptcha = r} onChange={this.recaptchaOnChange} sitekey={Config.recaptcha_key} />
Could be simplified to `r => this.recaptcha = r`

2019-12-11 04:58 UTC, holthelper commented
My fork was deleted accidentally by 3rd-party, made requested changes in new pr.

2019-12-11 04:58 UTC, closed without merging